direction: right
user question
table retrieve
qa retrieve
sql generation
SQL

user question -> table retrieve
user question -> qa retrieve
table retrieve ->  sql generation
qa retrieve ->  sql generation
sql generation -> SQL
